services:
  musicgen:
    build: .
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - ./shared/generated:/app/generated
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub:ro
    depends_on:
      - db
    networks:
      - musicnet
    runtime: nvidia  # <-- Add this line
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

